### ISSUE TITLE
beginner question

### ISSUE THREAD

**Issue by ghost** [hvianna/audioMotion-analyzer#23]
Hi

Can i use the script in a webbrowser locally?
Is there an example file I can look at?

I just want the script to work on audio I play on my computer, using an offlind html file.

Is this possible?

**Comment by hvianna** [comment]
Hello,

JavaScript security policies impose a lot of restrictions in local file mode - you can't import ES6 modules or read music files if not using http/https protocols. You can solve this by using a simple HTTP server to make files accessible via `http://localhost` - if you have node.js installed I'd recommend [http-server](https://github.com/http-party/http-server), otherwise check [this big list of http servers](https://gist.github.com/willurd/5720255).

Cheers!
